---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Palazzo HomeLab"
subtitle: ""
logo: "logo.png"

# NGINX http://192.168.1.113:81
header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"


# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Centrais"
    icon: "fas fa-bullseye"
    items:
      - name: "NAS Palazzo"
        logo: "assets/icons/homer-icons/png/synology.png"
        subtitle: "nas-palazzo"
        tag: "NAS"
        keywords: "Synology NAS DS418"
        url: "https://nas.palazzonet.duckdns.org"  # "https://192.168.1.129:6251/"
        target: "_blank"

      - name: "NAS Palazzo (IP)"
        logo: "assets/icons/homer-icons/png/synology.png"
        subtitle: "nas-palazzo via IP"
        tag: "NAS"
        keywords: "Synology NAS DS418"
        url: "https://192.168.1.129:6251/"
        target: "_blank"

      - name: "Proxmox"
        logo: "assets/icons/homer-icons/png/proxmox.png"
        subtitle: "palazzo.pve"
        tag: "VMs"
        url: "https://proxmox.palazzonet.duckdns.org"  # "https://192.168.1.108:8006"
        target: "_blank"

  - name: "Players"
    icon: "fas fa-film"
    items:
      - name: "Emby Server"
        logo: "assets/icons/homer-icons/png/emby.png"
        subtitle: "Emby"
        tag: "Media Server"
        keywords: "Emby server on synology NAS"
        url: "https://emby.palazzonet.duckdns.org"  # "https://192.168.1.129:8096/"
        target: "_blank"

      - name: "Plex Server"
        logo: "assets/icons/homer-icons/png/plex.png"
        subtitle: "Plex"
        tag: "Plex Server"
        keywords: "Plex server on synology NAS"
        url: "https://plex.palazzonet.duckdns.org"  # "https://192.168.1.129:32400/"
        target: "_blank"

  - name: "Downloads"
    icon: "fa fa-cloud-download"
    items:
      - name: "Sonarr"
        logo: "assets/icons/homer-icons/png/sonarr.png"
        subtitle: "Sonarr"
        tag: "Series"
        keywords: "Sonarr running on synology NAS"
        url: "https://sonarr.palazzonet.duckdns.org"  # "https://192.168.1.129:8989/"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/icons/homer-icons/png/radarr.png"
        subtitle: "Radarr"
        tag: "Filmes"
        keywords: "Radarr running on synology NAS"
        url: "https://radarr.palazzonet.duckdns.org"  # "https://192.168.1.129:8310"
        target: "_blank"

      - name: "Bazarr"
        logo: "assets/icons/homer-icons/png/bazarr.png"
        subtitle: "Bazarr"
        tag: "Legendas"
        keywords: "Bazarr running on synology NAS"
        url: "https://bazarr.palazzonet.duckdns.org"  #  "https://192.168.1.129:6767"
        target: "_blank"

  - name: "Indexadores"
    icon: "fa fa-rss-square"
    items:
      - name: "Prowlarr"
        logo: "assets/icons/homer-icons/png/prowlarr.png"
        subtitle: "Prowlarr"
        tag: "Indexador"
        keywords: "Prowlarr running on synology NAS"
        url: "https://prowlarr.palazzonet.duckdns.org"  #  "https://192.168.1.129:9696"
        target: "_blank"

      - name: "Jackett"
        logo: "assets/icons/homer-icons/png/jackett.png"
        subtitle: "Jackett"
        tag: "Indexador"
        keywords: "Jackett running on synology NAS"
        url: "https://jackett.palazzonet.duckdns.org"  #  "https://192.168.1.129:9117"
        target: "_blank"

  - name: "Rede"
    icon: "fas fa-ethernet"
    items:
      - name: "Roteador"
        logo: "assets/icons/homer-icons/png/tplink.png"
        subtitle: "TP-Link Deco AX3000 X55"
        tag: "Router"
        url: "https://192.168.1.1"
        target: "_blank"

      - name: "ADGuard"
        logo: "assets/icons/homer-icons/png/adguardhome.png"
        subtitle: "ADGuard DNS"
        tag: "DNS"
        url: "http://192.168.1.110"
        target: "_blank"

      - name: "NGINX"
        logo: "assets/icons/homer-icons/png/nginx_2.png"
        subtitle: "NGINX proxy manager"
        tag: "Proxy"
        url: "https://palazzonet.duckdns.org"  # "http://192.168.1.113:81"
        target: "_blank"